#!/usr/bin/env python3
"""Turn an export of the album's pages into the public demo's seed.

    python3 scripts/build-album-seed.py album_export.json --exclude <entry-id> ...

The export is the array of entries from the album's IndexedDB store (or the
older localStorage copy). Photos and AI-rendered page images are embedded in
it as base64 data URLs, several MB per page, so every data URL is written out
as a real image file under public/album/demo/pages/ and the seed only carries
URLs.

The album keeps its pages in IndexedDB ("memories-album"), importing the old
localStorage copy once on first run and ignoring it after that. So seed.js
writes IndexedDB directly, and index.html starts the app only after that
write commits (see build-album-app.py): the app never reads an album that's
half-seeded.

The seed is versioned by content hash. A returning visitor whose album holds
nothing but seeded pages (from this or any earlier seed, including the
localStorage-era demo and its "seed-N" placeholders) gets the new pages; a
visitor who has made pages of their own keeps their album untouched.
"""
import argparse
import base64
import hashlib
import json
import pathlib
import shutil

SITE = pathlib.Path(__file__).resolve().parent.parent
DEMO = SITE / "public" / "album" / "demo"
PAGES = DEMO / "pages"
URL_PREFIX = "/album/demo/pages/"
EXT = {"image/jpeg": "jpg", "image/png": "png", "image/webp": "webp", "image/gif": "gif"}


def externalize(data_url: str, written: set) -> str:
    """Write a data URL out as a content-addressed file; return its public URL."""
    if not isinstance(data_url, str) or not data_url.startswith("data:"):
        return data_url
    header, _, payload = data_url.partition(",")
    mime = header[5:].split(";")[0]
    data = base64.b64decode(payload) if ";base64" in header else payload.encode()
    name = f"{hashlib.sha1(data).hexdigest()[:12]}.{EXT.get(mime, 'bin')}"
    (PAGES / name).write_bytes(data)
    written.add(name)
    return URL_PREFIX + name


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("export", type=pathlib.Path)
    ap.add_argument("--exclude", nargs="*", default=[], help="entry ids to leave out")
    args = ap.parse_args()

    entries = json.loads(args.export.read_text())
    kept = [e for e in entries if e["id"] not in set(args.exclude)]
    if not kept:
        raise SystemExit("nothing left to seed after exclusions")

    PAGES.mkdir(parents=True, exist_ok=True)
    written: set = set()
    for e in kept:
        e["aiImage"] = externalize(e.get("aiImage"), written) if e.get("aiImage") else None
        # The original photos only feed the fallback layout. When a page has an
        # AI render, that render is all the album shows, so publishing the
        # originals would expose full-resolution personal photos no visitor sees.
        e["photos"] = [] if e["aiImage"] else [externalize(p, written) for p in e.get("photos", [])]

    # drop page images no longer referenced by any seeded entry
    for f in PAGES.iterdir():
        if f.name not in written:
            f.unlink()
    # the original placeholder seed borrowed Moodboard photos; nothing uses them now
    old_photos = DEMO / "photos"
    if old_photos.exists():
        shutil.rmtree(old_photos)

    seed = json.dumps(kept, separators=(",", ":"), ensure_ascii=False)
    version = hashlib.sha1(seed.encode()).hexdigest()[:12]

    (DEMO / "seed.js").write_text(f"""\
// Demo pages: real entries made in the album, AI-rendered pages included,
// generated by scripts/build-album-seed.py. Seed version {version}.
//
// index.html loads this instead of the app bundle and passes the bundle's URL
// in data-app; the app is started only once the seed has been written, so it
// never reads a half-seeded album.
(function () {{
  var APP = document.currentScript && document.currentScript.getAttribute("data-app");
  var VERSION = "{version}";
  var SEED = {seed};
  var VKEY = "demoSeedVersion", IDS = "demoSeedIds";
  // What the localStorage-era demo left behind, so its visitors carry over.
  var LEGACY_KEY = "scrapbook_entries_v2", LEGACY_IDS = "scrapbook_demo_seed_ids";

  function legacy(key) {{
    try {{ return JSON.parse(localStorage.getItem(key) || "[]"); }} catch (e) {{ return []; }}
  }}

  function seed(done) {{
    var req;
    try {{ req = indexedDB.open("memories-album", 1); }} catch (e) {{ return done(); }}
    // Same schema as src/journal/storage.ts, so whichever side opens first creates it identically.
    req.onupgradeneeded = function () {{
      var db = req.result;
      if (!db.objectStoreNames.contains("entries")) db.createObjectStore("entries", {{ keyPath: "id" }});
      if (!db.objectStoreNames.contains("meta")) db.createObjectStore("meta");
    }};
    req.onerror = req.onblocked = function () {{ done(); }};
    req.onsuccess = function () {{
      var db = req.result, tx;
      try {{ tx = db.transaction(["entries", "meta"], "readwrite"); }} catch (e) {{ db.close(); return done(); }}
      var entries = tx.objectStore("entries"), meta = tx.objectStore("meta");
      var version = meta.get(VKEY), seededIds = meta.get(IDS), migrated = meta.get("migratedFromLocalStorage");
      var keys = entries.getAllKeys();
      keys.onsuccess = function () {{
        var known = (seededIds.result || []).concat(legacy(LEGACY_IDS));
        function isSeeded(id) {{ return /^seed-/.test(id) || known.indexOf(id) !== -1; }}
        // The visitor's pages: what's in IndexedDB, plus, if the app hasn't
        // imported it yet, whatever the old localStorage demo gave them.
        var theirs = (keys.result || []).concat(
          migrated.result ? [] : legacy(LEGACY_KEY).map(function (e) {{ return e.id; }}));
        // Only replace an album the visitor hasn't written in themselves.
        if (theirs.every(isSeeded) && version.result !== VERSION) {{
          entries.clear();
          SEED.forEach(function (e) {{ entries.put(e); }});
          meta.put(VERSION, VKEY);
          meta.put(SEED.map(function (e) {{ return e.id; }}), IDS);
          // Stop the app importing the old localStorage copy over the seed.
          meta.put(true, "migratedFromLocalStorage");
        }}
      }};
      tx.oncomplete = tx.onerror = tx.onabort = function () {{ db.close(); done(); }};
    }};
  }}

  var started = false;
  function start() {{
    if (started || !APP) return;
    started = true;
    var s = document.createElement("script");
    s.type = "module";
    s.src = APP;
    document.head.appendChild(s);
  }}
  seed(start);
  setTimeout(start, 4000); // a stuck database must never keep the album from opening
}})();
""")

    size = sum((PAGES / n).stat().st_size for n in written)
    print(f"seeded {len(kept)} page(s), excluded {len(entries) - len(kept)}")
    print(f"page images: {len(written)} file(s), {size / 1024 / 1024:.1f} MB")
    print(f"seed.js: {(DEMO / 'seed.js').stat().st_size / 1024:.1f} KB  (version {version})")
    for e in sorted(kept, key=lambda e: e["date"]):
        print(f"  {e['date'][:10]}  {e['layoutSpec']['family']:<9}  "
              f"ai={'yes' if e['aiImage'] else 'no ':<3}  photos={len(e['photos'])}  {e['caption'][:60]!r}")


if __name__ == "__main__":
    main()
