#!/usr/bin/env python3
"""Turn an Album UI localStorage export into the public demo's seed pages.

    python3 scripts/build-album-seed.py album_export.json --exclude <entry-id> ...

The album stores its pages in localStorage, with photos and the AI-rendered
page image embedded as base64 data URLs. That can't be seeded as-is: a few
pages already approach the ~5 MB per-origin localStorage quota, and a failed
setItem leaves a visitor's album empty. So every data URL is written out as a
real image file under public/album/demo/pages/, and the seed only carries URLs.

The seed is versioned by content hash. A returning visitor whose album holds
nothing but seeded pages (from this or any earlier seed, including the
original "seed-N" placeholders) gets the new pages; a visitor who has made
pages of their own keeps their album untouched.
"""
import argparse
import base64
import hashlib
import json
import pathlib
import shutil

SITE = pathlib.Path(__file__).resolve().parent.parent
DEMO = SITE / "public" / "album" / "demo"
PAGES = DEMO / "pages"
URL_PREFIX = "/album/demo/pages/"
EXT = {"image/jpeg": "jpg", "image/png": "png", "image/webp": "webp", "image/gif": "gif"}


def externalize(data_url: str, written: set) -> str:
    """Write a data URL out as a content-addressed file; return its public URL."""
    if not isinstance(data_url, str) or not data_url.startswith("data:"):
        return data_url
    header, _, payload = data_url.partition(",")
    mime = header[5:].split(";")[0]
    data = base64.b64decode(payload) if ";base64" in header else payload.encode()
    name = f"{hashlib.sha1(data).hexdigest()[:12]}.{EXT.get(mime, 'bin')}"
    (PAGES / name).write_bytes(data)
    written.add(name)
    return URL_PREFIX + name


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("export", type=pathlib.Path)
    ap.add_argument("--exclude", nargs="*", default=[], help="entry ids to leave out")
    args = ap.parse_args()

    entries = json.loads(args.export.read_text())
    kept = [e for e in entries if e["id"] not in set(args.exclude)]
    if not kept:
        raise SystemExit("nothing left to seed after exclusions")

    PAGES.mkdir(parents=True, exist_ok=True)
    written: set = set()
    for e in kept:
        e["aiImage"] = externalize(e.get("aiImage"), written) if e.get("aiImage") else None
        # The original photos only feed the fallback layout. When a page has an
        # AI render, that render is all the album shows, so publishing the
        # originals would expose full-resolution personal photos no visitor sees.
        e["photos"] = [] if e["aiImage"] else [externalize(p, written) for p in e.get("photos", [])]

    # drop page images no longer referenced by any seeded entry
    for f in PAGES.iterdir():
        if f.name not in written:
            f.unlink()
    # the original placeholder seed borrowed Moodboard photos; nothing uses them now
    old_photos = DEMO / "photos"
    if old_photos.exists():
        shutil.rmtree(old_photos)

    seed = json.dumps(kept, separators=(",", ":"), ensure_ascii=False)
    version = hashlib.sha1(seed.encode()).hexdigest()[:12]

    (DEMO / "seed.js").write_text(f"""\
// Demo pages: real entries made in the album, AI-rendered pages included,
// generated by scripts/build-album-seed.py. Seed version {version}.
(function () {{
  var KEY = "scrapbook_entries_v2";
  var VKEY = "scrapbook_demo_seed";
  var VERSION = "{version}";
  var SEED = {seed};
  try {{
    var cur = JSON.parse(localStorage.getItem(KEY) || "[]");
    var seededIds = JSON.parse(localStorage.getItem(VKEY + "_ids") || "[]");
    // Untouched = every page came from a seed (this one, an earlier one, or the
    // original "seed-N" placeholders). Anything a visitor made themselves is kept.
    var untouched = cur.every(function (e) {{
      return /^seed-/.test(e.id) || seededIds.indexOf(e.id) !== -1;
    }});
    if (untouched && localStorage.getItem(VKEY) !== VERSION) {{
      localStorage.setItem(KEY, JSON.stringify(SEED));
      localStorage.setItem(VKEY, VERSION);
      localStorage.setItem(VKEY + "_ids", JSON.stringify(SEED.map(function (e) {{ return e.id; }})));
    }}
  }} catch (e) {{ /* private mode or quota: the album just opens empty */ }}
}})();
""")

    size = sum((PAGES / n).stat().st_size for n in written)
    print(f"seeded {len(kept)} page(s), excluded {len(entries) - len(kept)}")
    print(f"page images: {len(written)} file(s), {size / 1024 / 1024:.1f} MB")
    print(f"seed.js: {(DEMO / 'seed.js').stat().st_size / 1024:.1f} KB  (version {version})")
    for e in sorted(kept, key=lambda e: e["date"]):
        print(f"  {e['date'][:10]}  {e['layoutSpec']['family']:<9}  "
              f"ai={'yes' if e['aiImage'] else 'no ':<3}  photos={len(e['photos'])}  {e['caption'][:60]!r}")


if __name__ == "__main__":
    main()
